### ISSUE TITLE
Add support for VSTS pull request merge commit created event

### ISSUE THREAD

**Issue by pascalberger** [aspnet/WebHooks#124]
VSTS has added an event [Pull request merge commit created](https://www.visualstudio.com/en-us/docs/integrate/get-started/service-hooks/events#git.pullrequest.merged) which is not yet supported by this library.

**Comment by HenrikFrystykNielsen** [comment]
Would you  be willing to submit a pull request? :)

**Comment by pascalberger** [comment]
@HenrikFrystykNielsen Yes, I'm planning to use the library in a project where I would need this hook and will create a PR in this case

**Comment by pascalberger** [comment]
@HenrikFrystykNielsen I finally found some time to tackle this. PR is here: #155

**Comment by dougbu** [comment]
Marked as working because #155 exists.

**Comment by dougbu** [comment]
5ec458a3ba

**Comment by pascalberger** [comment]
@HenrikFrystykNielsen @dougbu Any chance to get a release containing this change?

**Comment by dougbu** [comment]
@pascalberger we are currently focused on solidifying the ASP.NET Core design and infrastructure. A v2.0.0 preview release would come soon after that calms down. But, we have not announced a more-specific roadmap.

I've opened #197 because packages aren't available while you wait for that preview release.
