### ISSUE TITLE
OneDrive on the roadmap?

### ISSUE THREAD

**Issue by SQL-MisterMagoo** [aspnet/WebHooks#15]
Hi, Just wondering if anyone is planning on implementing OneDrive webhooks into this project?
Thanks

**Comment by garora** [comment]
Earlier, I supposed to give a try with reference to [onedrive](https://dev.onedrive.com/misc/appfolder.htm). But, due to other priorities, I wouldn't able to start. I can give a try but not sure when. @HenrikFrystykNielsen - do you have any plans? I would love to take this initiative. Unfortunately, currently I have other priorities.

**Comment by HenrikFrystykNielsen** [comment]
Does OneDrive support WebHooks?

**Comment by garora** [comment]
I gone through link of documents but did not find anything related to
WebHooks.

**Comment by SQL-MisterMagoo** [comment]
It's in preview still, but the details are available here : [Service-to-service notifications (preview)](https://dev.onedrive.com/misc/webhooks.htm)

I was just wondering if it would be on the roadmap, as I would like to try it out, and this seems like the right tool for the job.

If it's not on the roadmap, that's all I need to know.

**Comment by HenrikFrystykNielsen** [comment]
We'd definitely be happy to have support for it! if you'd like to help submitting a PR then it will likely go faster ;)

**Comment by garora** [comment]
Documentation is moved here [WebHooks](https://dev.onedrive.com/webhooks/webhooks.htm).
@SQL-MisterMagoo , @HenrikFrystykNielsen  - is anyone working on this?

**Comment by HenrikFrystykNielsen** [comment]
Not at the moment...

**Comment by garora** [comment]
I'd try it after completing one, I am working on.
On 05/06/2016 1:16 AM, "Henrik Frystyk Nielsen" <notifications@github.com>
wrote:

Not at the moment...

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/aspnet/WebHooks/issues/15#issuecomment-223774537>, or mute
the thread
<https://github.com/notifications/unsubscribe/AA6_OVZ85-dq1_nmiDGaTMntPiK1_wXvks5qIdYrgaJpZM4GNu4R>
.

**Comment by garora** [comment]
I'm going to pick this one!

**Comment by HenrikFrystykNielsen** [comment]
awesome!

**Comment by garora** [comment]
Putting it on hold due to [Issue#92](https://github.com/aspnet/WebHooks/issues/92)

**Comment by garora** [comment]
Still waiting for a solution for #92

**Comment by aspnet-hello** [comment]
This issue was copied to aspnet/Home#2951

**Comment by aspnet-hello** [comment]
This issue was copied to aspnet/Home#2952

**Comment by aspnet-hello** [comment]
This issue was copied to aspnet/AspNetWebHooks#15

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/AspLabs#56
