### ISSUE TITLE
Remove maximum size limit on GitHubWebHook receiver key

### ISSUE THREAD

**Issue by pranavkm** [aspnet/WebHooks#245]
We limit it to 128 characters. There really isn't a good reason to have a max limit.

**Comment by pranavkm** [comment]
cc @dougbu \ @blowdart

**Comment by dougbu** [comment]
Nothing about this is specific to the GitHub receiver. For example, one common receiver configuration is to simply stick the secret key into a `code` query parameter. The secret key must be 32 to 128 characters long in that case.

We should remove the maximums everywhere except perhaps for the Salesforce receiver. In that one case, the sender provides the secret key and the limit ensures it was copied from the right spot. ("Perhaps" because I'm not sure that check is worthwhile either.)

**Comment by dougbu** [comment]
Get rid of limit on thingie in our configuration store&hellip;

**Comment by dougbu** [comment]
Realized (after staring at Identity's `StoreOptions.MaxLengthForKeys` a bit) there **is** a good reason to limit the size of secret keys in a WebHooks application. The keys are stored in `IConfiguration` and configuration stores may certainly include (say) a SQL database.

New idea: Instead of removing the maximum secret key length entirely, make the maximum a `public` property (somewhere) or perhaps add our first `WebHookOptions` property.

@blowdart do you have a preference on how this setting would be exposed?

**Comment by dougbu** [comment]
Updated [previous comment](https://github.com/aspnet/WebHooks/issues/245#issuecomment-365698313). Since user has control of the secret keys they use and the corresponding SQL schema, database restrictions are _not_ a good reason to keep the maximum length restrictions.

**Comment by dougbu** [comment]
30897e047f
